// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbt60n6bcqt8CMeofNSNoKkLzfaQZNa1Y',
    appId: '1:1059987097918:web:45fd11d71a6b7d6a9e446f',
    messagingSenderId: '1059987097918',
    projectId: 'bookinghospitalapp',
    authDomain: 'bookinghospitalapp.firebaseapp.com',
    storageBucket: 'bookinghospitalapp.firebasestorage.app',
    measurementId: 'G-89ZLLZJ2CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0avkccX9H-6wI_bHYYmX2iYQ7XQQTaC8',
    appId: '1:1059987097918:android:842b2dae492830a39e446f',
    messagingSenderId: '1059987097918',
    projectId: 'bookinghospitalapp',
    storageBucket: 'bookinghospitalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfcL5tu5i0iiOROQ12k6S4kC5yaL0o31k',
    appId: '1:1059987097918:ios:819c56d87fe779929e446f',
    messagingSenderId: '1059987097918',
    projectId: 'bookinghospitalapp',
    storageBucket: 'bookinghospitalapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
